<?php

function my_utilities_init() {
	global $user;
}

/**
 * 	Implementation of hook_theme().
 */
function my_utilities_theme() {
	return array(
		'intro_page' => array(
			'template' =>'templates/intro',
		),
		'home_page' => array(
			'template' =>'templates/home',
		),
		'distribution_page' => array(
			'template' =>'templates/distribution',
		),
		'recruitment_page' => array(
			'template' =>'templates/recruitment',
		),
		'product_page' => array(
			'template' =>'templates/product',
		),
		'news_page' => array(
			'template' =>'templates/news',
		)
	);
}

function my_intro(){
	return theme('intro_page');
}

function my_home(){
	return theme('home_page');
}

function my_distribution(){
	return theme('distribution_page');
}

function my_recruitment(){
	return theme('recruitment_page');
}

function my_product(){
	return theme('product_page');
}

function my_news(){
	return theme('news_page');
}

/**
 * 	Implementation of hook_menu().
 */
function my_utilities_menu() {
	global $user;
	$items = array();
	$items['home'] = array(
		'title' => t(''),
		'page callback' => 'my_home',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['intro'] = array(
		'title' => t(''),
		'page callback' => 'my_intro',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['product'] = array(
		'title' => t(''),
		'page callback' => 'my_product',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['news'] = array(
		'title' => t(''),
		'page callback' => 'my_news',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['distribution'] = array(
		'title' => t(''),
		'page callback' => 'my_distribution',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['recruitment'] = array(
		'title' => t(''),
		'page callback' => 'my_recruitment',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}
