<?php
// $Id: vsk_utilities.module,v 1.0 2012/02/18 Linh Tran Exp $

/*
 *	Implementation of hook_init().
 */

function vsk_utilities_init() {	
	global $user;
	drupal_add_css(drupal_get_path('module', 'vsk_utilities') .'/css/jquery-ui.css');
	drupal_add_css(drupal_get_path('module', 'vsk_utilities') .'/css/vsk_utilities.css');
	drupal_add_js(drupal_get_path('module', 'vsk_utilities') .'/js/vsk_utilities.js','footer');
}

/**
 * 	Implementation of hook_theme().
 */
function vsk_utilities_theme() {
	return array(		
		'home_page' => array(
			'template' =>'templates/home',			
		),
		'lai_suat' => array(
			'template' =>'templates/lai-suat',			
		),
		'ket_qua' => array(
			'template' =>'templates/ket-qua',			
		),
		'banner_block' => array(
			'template' =>'templates/banner-block',			
		),
		'form_block' => array(
			'template' =>'templates/form-block',			
		),
		'menu_block' => array(
			'template' => 'templates/menu-block',
		),
		'menuxecu_block' => array(
			'template' => 'templates/menuxecu-block',
		),
		'detail_block' => array(
			'template' => 'templates/detail-block',
		),
		'xecu_block' => array(
			'template' => 'templates/xecu-block',
		),
		'product_page' => array(
			'template' => 'templates/product-page',
		),
		'xecu_page' => array(
			'template' => 'templates/xecu-page',
		),
		'product_cate' => array(
			'template' => 'templates/product-cate',
			'arguments' => array('cid' => NULL),
		),
		'xecu_cate' => array(
			'template' => 'templates/xecu-cate',
			'arguments' => array('cid' => NULL),
		),
		'product_detail' => array(
			'template' => 'templates/product-detail',
			'arguments' => array('pid' => NULL),
		),
		'xecu_detail' => array(
			'template' => 'templates/xecu-detail',
			'arguments' => array('pid' => NULL),
		),
		'product_block' => array(
			'template' => 'templates/product-block',
		),
		'product_relation' => array(
			'template' => 'templates/product-relation',
		),
		'service_block' => array(
			'template' => 'templates/service-block',
		),
		'other_news' => array(
			'template' =>'templates/other-news',
			'arguments' => array('nid' => null),
		),
		'gmap_page' => array(
			'template' => 'templates/gmap-page',
		),
		'contact_page' => array(
			'template' => 'templates/contact-page',
		),
		'scroll_left' => array(
			'template' => 'templates/scroll-left',
		),
		'menu_footer' => array(
			'template' => 'templates/menu-footer',
		),
		'slide_show' => array(
			'template' =>'templates/slide-show',
			'arguments' => array('width' => null, 'height' => null),					
		),
	);	
}
function vsk_home(){
	return theme('home_page');
}
function vsk_lai_suat(){
	return theme('lai_suat');
}
function vsk_ket_qua(){
	print theme('ket_qua');
}
function vsk_product(){
	return theme('product_page');
}
function vsk_xecu(){
	return theme('xecu_page');
}
function vsk_product_cate($cid){
	return theme('product_cate',$cid);
}
function vsk_xecu_cate($cid){
	return theme('xecu_cate',$cid);
}
function vsk_product_detail($pid){
	return theme('product_detail',$pid);
}
function vsk_xecu_detail($pid){
	return theme('xecu_detail',$pid);
}
function vsk_contact(){
	return theme('contact_page');
}
/**
 * 	Implementation of hook_menu().
 */
function vsk_utilities_menu() {
	global $user;
	$items = array();
	$items['trang-chu'] = array(
		'title' => t(''),
		'page callback' => 'vsk_home',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	$items['mua-xe-o-to-tra-gop'] = array(
		'title' => t('Mua xe ô-tô trả góp'),
		'page callback' => 'vsk_lai_suat',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	$items['ket-qua'] = array(
		'title' => t(''),
		'page callback' => 'vsk_ket_qua',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	/*
	$items['lien-he'] = array(
		'title' => t('Liên hệ'),
		'page callback' => 'vsk_contact',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	*/
	$items['san-pham'] = array(
		'title' => t('Sản phẩm'),
		'page callback' => 'vsk_product',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	$items['san-pham/%/%'] = array(
		'title' => t(''),
		'page callback' => 'vsk_product_cate',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	$items['chi-tiet-sp/%/%'] = array(
		'title' => t(''),
		'page callback' => 'vsk_product_detail',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	
	$items['xe-cu'] = array(
		'title' => t('Sản phẩm xe cũ'),
		'page callback' => 'vsk_xecu',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	$items['xe-cu/%/%'] = array(
		'title' => t(''),
		'page callback' => 'vsk_xecu_cate',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	$items['chi-tiet-xc/%/%'] = array(
		'title' => t(''),
		'page callback' => 'vsk_xecu_detail',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	// form
	$items['dang-ky-nhan-catalogue'] = array(
		'title' => t('Đăng ký nhận catalogue'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('reg_catalogue'),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	$items['dang-ky-lai-xe-thu'] = array(
		'title' => t('Đăng ký lái thử xe'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('reg_drive'),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	$items['dang-ky-mua-xe'] = array(
		'title' => t('Đăng ký lái thử xe'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('reg_buy'),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	$items['dang-ky-bao-duong'] = array(
		'title' => t('Đăng ký lái thử xe'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('reg_maintenance'),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,		
    );
	return $items;
}
/**
 * Implementation of hook_user().
 */
function vsk_utilities_user($op, &$edit, &$account, $category = NULL){
	global $user;
	switch($op) {				
		case 'login':			
			//drupal_goto('');			
			break;
	}
}

/**
 * Implementation of hook_block()
 */
function vsk_utilities_block($op = 'list', $delta = 0, $edit = array()){
	if ($op == 'list') {
		//Menu
		$blocks[0] = array(
			'info' => t('Menu Block'),
			'cache' => BLOCK_NO_CACHE
		);		
		//End menu
		$blocks[1] = array(
			'info' => t('Gmap Block'),
			'cache' => BLOCK_NO_CACHE
		);
		$blocks[2] = array(
			'info' => t('Banner Block'),
			'cache' => BLOCK_NO_CACHE
		);
		$blocks[3] = array(
			'info' => t('SlideShow block'),
			'cache' => BLOCK_CACHE_GLOBAL
		);
		$blocks[4] = array(
			'info' => t('Scroll block'),
			'cache' => BLOCK_CACHE_GLOBAL
		);
		$blocks[5] = array(
			'info' => t('Menu footer'),
			'cache' => BLOCK_CACHE_GLOBAL
		);
		$blocks[6] = array(
			'info' => t('Form block'),
			'cache' => BLOCK_CACHE_GLOBAL
		);
		$blocks[7] = array(
			'info' => t('Detail block'),
			'cache' => BLOCK_CACHE_GLOBAL
		);
		$blocks[8] = array(
			'info' => t('Xe cu block'),
			'cache' => BLOCK_CACHE_GLOBAL
		);
		$blocks[9] = array(
			'info' => t('Menu xe cu block'),
			'cache' => BLOCK_CACHE_GLOBAL
		);
		return $blocks;
	} elseif ($op == 'view') {
		switch($delta) {
			// Menu
			case 0:
				$block = array(
					'subject' => t(''),
					'content' => theme('menu_block'),
				);				
			break;			
			//End menu
			case 1:
				$block = array(
					'subject' => t(''),
					'content' => theme('gmap_page'),
				);				
			break;
			case 2:
				$block = array(
					'subject' => t(''),
					'content' => theme('banner_block'),
				);				
			break;
			case 3:				
				$block = array(
					'subject' => t(''),
					'content' => theme('slide_show',898,320),
				);				
			break;
			case 4:				
				$block = array(
					'subject' => t(''),
					'content' => theme('scroll_left'),
				);				
			break;
			case 5:				
				$block = array(
					'subject' => t(''),
					'content' => theme('menu_footer'),
				);				
			break;
			case 6:				
				$block = array(
					'subject' => t(''),
					'content' => theme('form_block'),
				);				
			break;
			case 7:				
				$block = array(
					'subject' => t(''),
					'content' => theme('detail_block'),
				);				
			break;
			case 8:				
				$block = array(
					'subject' => t(''),
					'content' => theme('xecu_block'),
				);				
			break;
			case 9:				
				$block = array(
					'subject' => t(''),
					'content' => theme('menuxecu_block'),
				);				
			break;
		}
		return $block;
	}
}

// Func set message value
function smv($var){
	drupal_set_message('<pre>'. $var .'</pre>');
}
// Func set message object
function smo($var){
	drupal_set_message('<pre>'. print_r($var,1) .'</pre>');
}
function unicode_str_replace($value)
{
	$value = str_replace(" ","-", $value);
    #---------------------------------a^
    $value = str_replace("."," .", $value);
    $value = str_replace("?"," ?", $value);
    #---------------------------------a^
    $value = str_replace("ấ", "a", $value);
    $value = str_replace("ầ", "a", $value);
    $value = str_replace("ẩ", "a", $value);
    $value = str_replace("ẫ", "a", $value);
    $value = str_replace("ậ", "a", $value);
    #---------------------------------A^
    $value = str_replace("Ấ", "a", $value);
    $value = str_replace("Ầ", "a", $value);
    $value = str_replace("Ẩ", "a", $value);
    $value = str_replace("Ẫ", "a", $value);
    $value = str_replace("Ậ", "a", $value);
    #---------------------------------a(
    $value = str_replace("ắ", "a", $value);
    $value = str_replace("ằ", "a", $value);
    $value = str_replace("ẳ", "a", $value);
    $value = str_replace("ẵ", "a", $value);
    $value = str_replace("ặ", "a", $value);
    #---------------------------------A(
    $value = str_replace("Ắ", "a", $value);
    $value = str_replace("Ằ", "a", $value);
    $value = str_replace("Ẳ", "a", $value);
    $value = str_replace("Ẵ", "a", $value);
    $value = str_replace("Ặ", "a", $value);
    #---------------------------------a
    $value = str_replace("á", "a", $value);
    $value = str_replace("à", "a", $value);
    $value = str_replace("ả", "a", $value);
    $value = str_replace("ã", "a", $value);
    $value = str_replace("ạ", "a", $value);
    $value = str_replace("â", "a", $value);
    $value = str_replace("ă", "a", $value);
    #---------------------------------A
    $value = str_replace("Á", "a", $value);
    $value = str_replace("À", "a", $value);
    $value = str_replace("Ả", "a", $value);
    $value = str_replace("Ã", "a", $value);
    $value = str_replace("Ạ", "a", $value);
    $value = str_replace("Â", "a", $value);
    $value = str_replace("Ă", "a", $value);
    #---------------------------------e^
    $value = str_replace("ế", "e", $value);
    $value = str_replace("ề", "e", $value);
    $value = str_replace("ể", "e", $value);
    $value = str_replace("ễ", "e", $value);
    $value = str_replace("ệ", "e", $value);
    #---------------------------------E^
    $value = str_replace("Ế", "e", $value);
    $value = str_replace("Ề", "e", $value);
    $value = str_replace("Ể", "e", $value);
    $value = str_replace("Ễ", "e", $value);
    $value = str_replace("Ệ", "e", $value);
    #---------------------------------e
    $value = str_replace("é", "e", $value);
    $value = str_replace("è", "e", $value);
    $value = str_replace("ẻ", "e", $value);
    $value = str_replace("ẽ", "e", $value);
    $value = str_replace("ẹ", "e", $value);
    $value = str_replace("ê", "e", $value);
    #---------------------------------E
    $value = str_replace("É", "e", $value);
    $value = str_replace("È", "e", $value);
    $value = str_replace("Ẻ", "e", $value);
    $value = str_replace("Ẽ", "e", $value);
    $value = str_replace("Ẹ", "e", $value);
    $value = str_replace("Ê", "e", $value);
    #---------------------------------i
    $value = str_replace("í", "i", $value);
    $value = str_replace("ì", "i", $value);
    $value = str_replace("ỉ", "i", $value);
    $value = str_replace("ĩ", "i", $value);
    $value = str_replace("ị", "i", $value);
    #---------------------------------I
    $value = str_replace("Í", "i", $value);
    $value = str_replace("Ì", "i", $value);
    $value = str_replace("Ỉ", "i", $value);
    $value = str_replace("Ĩ", "i", $value);
    $value = str_replace("Ị", "i", $value);
    #---------------------------------o^
    $value = str_replace("ố", "o", $value);
    $value = str_replace("ồ", "o", $value);
    $value = str_replace("ổ", "o", $value);
    $value = str_replace("ỗ", "o", $value);
    $value = str_replace("ộ", "o", $value);
    #---------------------------------O^
    $value = str_replace("Ố", "o", $value);
    $value = str_replace("Ồ", "o", $value);
    $value = str_replace("Ổ", "o", $value);
    $value = str_replace("Ô", "o", $value);
    $value = str_replace("Ộ", "o", $value);
    #---------------------------------o*
    $value = str_replace("ớ", "o", $value);
    $value = str_replace("ờ", "o", $value);
    $value = str_replace("ở", "o", $value);
    $value = str_replace("ỡ", "o", $value);
    $value = str_replace("ợ", "o", $value);
    #---------------------------------O*
    $value = str_replace("Ớ", "o", $value);
    $value = str_replace("Ờ", "o", $value);
    $value = str_replace("Ở", "o", $value);
    $value = str_replace("Ỡ", "o", $value);
    $value = str_replace("Ợ", "o", $value);
    #---------------------------------u*
    $value = str_replace("ứ", "u", $value);
    $value = str_replace("ừ", "u", $value);
    $value = str_replace("ử", "u", $value);
    $value = str_replace("ữ", "u", $value);
    $value = str_replace("ự", "u", $value);
    #---------------------------------U*
    $value = str_replace("Ứ", "u", $value);
    $value = str_replace("Ừ", "u", $value);
    $value = str_replace("Ử", "u", $value);
    $value = str_replace("Ữ", "u", $value);
    $value = str_replace("Ự", "u", $value);
    #---------------------------------y
    $value = str_replace("ý", "y", $value);
    $value = str_replace("ỳ", "y", $value);
    $value = str_replace("ỷ", "y", $value);
    $value = str_replace("ỹ", "y", $value);
    $value = str_replace("ỵ", "y", $value);
    #---------------------------------Y
    $value = str_replace("Ý", "y", $value);
    $value = str_replace("Ỳ", "y", $value);
    $value = str_replace("Ỷ", "y", $value);
    $value = str_replace("Ỹ", "y", $value);
    $value = str_replace("Ỵ", "y", $value);
    #---------------------------------DD
    $value = str_replace("Đ", "d", $value);
    $value = str_replace("Đ", "d", $value);
    $value = str_replace("đ", "d", $value);
    #---------------------------------o
    $value = str_replace("ó", "o", $value);
    $value = str_replace("ò", "o", $value);
    $value = str_replace("ỏ", "o", $value);
    $value = str_replace("õ", "o", $value);
    $value = str_replace("ọ", "o", $value);
    $value = str_replace("ô", "o", $value);
    $value = str_replace("ơ", "o", $value);
    #---------------------------------O
    $value = str_replace("Ó", "o", $value);
    $value = str_replace("Ò", "o", $value);
    $value = str_replace("Ỏ", "o", $value);
    $value = str_replace("Õ", "o", $value);
    $value = str_replace("Ọ", "o", $value);
    $value = str_replace("Ô", "o", $value);
    $value = str_replace("Ơ", "ou", $value);
    #---------------------------------u
    $value = str_replace("ú", "u", $value);
    $value = str_replace("ù", "u", $value);
    $value = str_replace("ủ", "u", $value);
    $value = str_replace("ũ", "u", $value);
    $value = str_replace("ụ", "u", $value);
    $value = str_replace("ư", "u", $value);
    #---------------------------------U
    $value = str_replace("Ú", "u", $value);
    $value = str_replace("Ù", "u", $value);
    $value = str_replace("Ủ", "u", $value);
    $value = str_replace("Ũ", "u", $value);
    $value = str_replace("Ụ", "u", $value);
    $value = str_replace("Ư", "u", $value);
    #---------------------------------
	$value = str_replace("--","-", $value);
	$value = str_replace("--","-", $value);
    return strtolower($value);
} 
function product_home($tid){
	$obj = db_query("SELECT node.nid AS nid,
	   node_data_field_product_category_image.field_product_category_image_fid AS image_fid,
	   node.type AS node_type,
	   node.vid AS node_vid,
	   term_data.name AS name,
	   term_data.vid AS term_data_vid,
	   term_data.tid AS tid,
	   term_data.description AS description
	 FROM node node 
	 LEFT JOIN content_type_product_category node_data_field_product_category_image ON node.vid = node_data_field_product_category_image.vid
	 LEFT JOIN term_node term_node ON node.vid = term_node.vid
	 LEFT JOIN term_data term_data ON term_node.tid = term_data.tid
	 WHERE (node.status <> 0) AND (node.type in ('product_category')) AND (node.vid IN (
	  SELECT tn.vid FROM term_node tn
	  WHERE tn.tid  = %d
	  ))
	",$tid);
	$obj_rs = db_fetch_object($obj);
	$arr = field_file_load($obj_rs->image_fid);
	$path = $arr['filepath'];
	
	$product = new stdClass;
	$product->tid = $obj_rs->tid;
	$product->term_name = $obj_rs->name;
	$product->description = $obj_rs->description;
	$product->path = $path;
	
	return $product;
}
function get_taxo($arr = array()){
	foreach($arr AS $key => $value){
		return $value;
	}
}
function check_child($tid){
	$child = taxonomy_get_children($tid);
	if($child){
		return true;
	} else {
		return false;
	}
}
function loai_xe(){
	$obj = db_query("SELECT node.nid AS nid, 
			node.title AS node_title, 
			node.language AS node_language, 
			node.created AS node_created 
		FROM node node  
		WHERE (node.status <> 0) AND (node.type in ('loaixe')) 
		ORDER BY node_created ASC");
	$aLoaiXe = array();
	$aLoaiXe[] = t('Vui lòng chọn');
	while($obj_rs = db_fetch_object($obj)){
		$aLoaiXe[$obj_rs->nid] = $obj_rs->node_title;
	}
	return $aLoaiXe;
}
//form
function reg_catalogue($form_state){
	$form['quan_tam'] = array(
		'#type' => 'fieldset',
		'#title' => t('Quí vị quan tâm loại xe nào?'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['quan_tam']['loai_xe'] = array(
		'#type' => 'select',
		'#title' => t('Loại xe'),
		'#default_value'=> '',
		'#options' => loai_xe(),
		'#required' => TRUE,
	);
	$form['quan_tam']['series'] = array(
		'#type' => 'select',
		'#title' => t('Series'),
		'#default_value'=> '',
		'#options' => array(		
			'' => t('Vui lòng chọn'),
		),
		'#required' => FALSE,
	);
	
	$form['personal_info'] = array(
		'#type' => 'fieldset',
		'#title' => t('Thông tin cá nhân'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['personal_info']['noi_lam_viec'] = array(
		'#type' => 'textfield',
		'#title' => t('Nơi làm việc'),
		'#default_value' => '',
		'#required' => false,
	);
	$form['personal_info']['danh_xung'] = array(
		'#type' => 'select',
		'#title' => t('Danh xưng'),
		'#default_value'=> '',
		'#options' => array(
			'Ông' => t('Ông'),
			'Bà' => t('Bà'),
			'Anh' => t('Anh'),
			'Chị' => t('Chị'),
		),
		'#required' => TRUE,
	);
	$form['personal_info']['ho_ten'] = array(
		'#type' => 'textfield',
		'#title' => t('Họ và tên'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['do_tuoi'] = array(
		'#type' => 'select',
		'#title' => t('Bạn đang ở độ tuổi nào'),
		'#default_value'=> '',
		'#options' => array(		
			'' => t('Vui lòng chọn'),
			'<18' => t('<18'),
			'18-24' => t('18-24'),
			'25-34' => t('25-34'),
			'35-44' => t('35-44'),
			'45-54' => t('45-54'),
			'55-64' => t('55-64'),
			'>64' => t('>64'),
		),
		'#required' => FALSE,
	);
	$form['personal_info']['gioi_tinh'] = array(
		'#type' => 'select',
		'#title' => t('Giới tính'),
		'#default_value'=> '',
		'#options' => array(		
			'' => t('Vui lòng chọn'),
			'Nam' => t('Nam'),
			'Nữ' => t('Nữ'),
		),
		'#required' => FALSE,
	);
	
	$form['personal_info']['email'] = array(
		'#type' => 'textfield',
		'#title' => t('Email'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['dien_thoai'] = array(
		'#type' => 'textfield',
		'#title' => t('Điện thoại'),
		'#default_value' => '',
		'#required' => FALSE,
	);
	/*
	$form['dien_thoai'] = array(
		'#type' => 'fieldset',
		'#title' => t('Điện thoại liên hệ (vui lòng điền cả mã vùng)'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['dien_thoai']['nha_rieng'] = array(
		'#type' => 'textfield',
		'#title' => t('Điện thoại nhà riêng'),
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['dien_thoai']['co_quan'] = array(
		'#type' => 'textfield',
		'#title' => t('Điện thoại cơ quan'),
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['dien_thoai']['di_dong'] = array(
		'#type' => 'textfield',
		'#title' => t('Điện thoại di động'),
		'#default_value' => '',
		'#required' => FALSE,
	);
	*/
	$form['contact'] = array(
		'#type' => 'fieldset',
		'#title' => t(''),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['contact']['dia_chi'] = array(
		'#type' => 'textarea',
		'#title' => t('Địa chỉ liên hệ'),
		'#default_value' => '',
		'#required' => TRUE,
		'#resizable' => FALSE,
	);
	
	$form['send'] = array(
		'#type' => 'submit',
		'#value' => t('Gửi đi'),
		'#prefix'=> '',
		'#suffix'=> '',
	);
	return $form;
}
function reg_catalogue_submit($form, &$form_state){
	global $user;
	$node = new stdClass();
	$node->status = 1;
	$node->type = 'catalogue';
	$node->created = time();
	$node->changed  = time();
	$node->title  = $form['contact']['dia_chi']['#value'];
	$node->uid = $user->uid;
	$node->field_catalogue_loaixe[0]['value'] = $form['quan_tam']['loai_xe'];
	$node->field_catalogue_series[0]['value'] = $form['quan_tam']['series']['#value'];
	$node->field_catalogue_noilamviec[0]['value'] = $form['personal_info']['noi_lam_viec']['#value'];
	$node->field_catalogue_danhxung[0]['value'] = $form['personal_info']['danh_xung']['#value'];
	$node->field_catalogue_hoten[0]['value'] = $form['personal_info']['ho_ten']['#value'];
	$node->field_catalogue_dotuoi[0]['value'] = $form['personal_info']['do_tuoi']['#value'];
	$node->field_catalogue_gioitinh[0]['value'] = $form['personal_info']['gioi_tinh']['#value'];
	$node->field_catalogue_email[0]['value'] = $form['personal_info']['email']['#value'];
	$node->field_catalogue_dienthoai[0]['value'] = $form['personal_info']['dien_thoai']['#value'];
	$node = node_save($node);
	smo('Thông tin của bạn đã được gởi thành công!');
}

function reg_drive($form_state){
	$form['quan_tam'] = array(
		'#type' => 'fieldset',
		'#title' => t('Quí vị quan tâm loại xe nào?'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['quan_tam']['loai_xe'] = array(
		'#type' => 'select',
		'#title' => t('Loại xe'),
		'#default_value'=> '',
		'#options' => loai_xe(),
		'#required' => TRUE,
	);
	$form['quan_tam']['series'] = array(
		'#type' => 'select',
		'#title' => t('Series'),
		'#default_value'=> '',
		'#options' => array(		
			'' => t('Vui lòng chọn'),
		),
		'#required' => FALSE,
	);
	
	$form['personal_info'] = array(
		'#type' => 'fieldset',
		'#title' => t('Thông tin cá nhân'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['personal_info']['noi_lam_viec'] = array(
		'#type' => 'textfield',
		'#title' => t('Nơi làm việc'),
		'#default_value' => '',
		'#required' => false,
	);
	$form['personal_info']['danh_xung'] = array(
		'#type' => 'select',
		'#title' => t('Danh xưng'),
		'#default_value'=> '',
		'#options' => array(
			'Ông' => t('Ông'),
			'Bà' => t('Bà'),
			'Anh' => t('Anh'),
			'Chị' => t('Chị'),
		),
		'#required' => TRUE,
	);
	$form['personal_info']['ho_ten'] = array(
		'#type' => 'textfield',
		'#title' => t('Họ và tên'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['do_tuoi'] = array(
		'#type' => 'select',
		'#title' => t('Bạn đang ở độ tuổi nào'),
		'#default_value'=> '',
		'#options' => array(		
			'' => t('Vui lòng chọn'),
			'<18' => t('<18'),
			'18-24' => t('18-24'),
			'25-34' => t('25-34'),
			'35-44' => t('35-44'),
			'45-54' => t('45-54'),
			'55-64' => t('55-64'),
			'>64' => t('>64'),
		),
		'#required' => FALSE,
	);
	$form['personal_info']['gioi_tinh'] = array(
		'#type' => 'select',
		'#title' => t('Giới tính'),
		'#default_value'=> '',
		'#options' => array(		
			'' => t('Vui lòng chọn'),
			'Nam' => t('Nam'),
			'Nữ' => t('Nữ'),
		),
		'#required' => FALSE,
	);
	$form['personal_info']['email'] = array(
		'#type' => 'textfield',
		'#title' => t('Email'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['dien_thoai'] = array(
		'#type' => 'textfield',
		'#title' => t('Điện thoại'),
		'#default_value' => '',
		'#required' => FALSE,
	);
	/*
	$form['dien_thoai'] = array(
		'#type' => 'fieldset',
		'#title' => t('Điện thoại liên hệ (vui lòng điền cả mã vùng)'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['dien_thoai']['nha_rieng'] = array(
		'#type' => 'textfield',
		'#title' => t('Điện thoại nhà riêng'),
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['dien_thoai']['co_quan'] = array(
		'#type' => 'textfield',
		'#title' => t('Điện thoại cơ quan'),
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['dien_thoai']['di_dong'] = array(
		'#type' => 'textfield',
		'#title' => t('Điện thoại di động'),
		'#default_value' => '',
		'#required' => FALSE,
	);
	*/
	$form['contact'] = array(
		'#type' => 'fieldset',
		'#title' => t(''),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['contact']['dia_chi'] = array(
		'#type' => 'textarea',
		'#title' => t('Địa chỉ liên hệ'),
		'#default_value' => '',
		'#required' => TRUE,
		'#resizable' => FALSE,
	);
	
	$form['send'] = array(
		'#type' => 'submit',
		'#value' => t('Gửi đi'),
		'#prefix'=> '',
		'#suffix'=> '',
	);
	return $form;
}
function reg_drive_submit($form, &$form_state){
	global $user;
	$node = new stdClass();
	$node->status = 1;
	$node->type = 'drive';
	$node->created = time();
	$node->changed  = time();
	$node->title  = $form['contact']['dia_chi']['#value'];
	$node->uid = $user->uid;
	$node->field_drive_loaixe[0]['value'] = $form['quan_tam']['loai_xe'];
	$node->field_drive_series[0]['value'] = $form['quan_tam']['series']['#value'];
	$node->field_drive_noilamviec[0]['value'] = $form['personal_info']['noi_lam_viec']['#value'];
	$node->field_drive_danhxung[0]['value'] = $form['personal_info']['danh_xung']['#value'];
	$node->field_drive_hoten[0]['value'] = $form['personal_info']['ho_ten']['#value'];
	$node->field_drive_dotuoi[0]['value'] = $form['personal_info']['do_tuoi']['#value'];
	$node->field_drive_gioitinh[0]['value'] = $form['personal_info']['gioi_tinh']['#value'];
	$node->field_drive_email[0]['value'] = $form['personal_info']['email']['#value'];
	$node->field_drive_dienthoai[0]['value'] = $form['personal_info']['dien_thoai']['#value'];
	$node = node_save($node);
	smo('Thông tin của bạn đã được gởi thành công!');
}

function reg_buy($form_state){
	$form['quan_tam'] = array(
		'#type' => 'fieldset',
		'#title' => t('Quí vị quan tâm loại xe nào?'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['quan_tam']['loai_xe'] = array(
		'#type' => 'select',
		'#title' => t('Loại xe'),
		'#default_value'=> '',
		'#options' => loai_xe(),
		'#required' => FALSE,
	);
	$form['quan_tam']['thoi_diem_mua'] = array(
		'#type' => 'select',
		'#title' => t('Thời điểm quyết định mua xe'),
		'#default_value'=> '1 tháng',
		'#options' => array(		
			'1 tháng' => t('1 tháng'),
			'2 tháng' => t('2 tháng'),
			'3 tháng' => t('3 tháng'),
			'khác' => t('khác'),
		),
		'#required' => FALSE,
	);
	$form['quan_tam']['yeu_cau_them'] = array(
		'#type' => 'textarea',
		'#title' => t('Yêu cầu thêm'),
		'#default_value' => '',
		'#required' => FALSE,
		'#resizable' => FALSE,
	);
	
	$form['personal_info'] = array(
		'#type' => 'fieldset',
		'#title' => t('Thông tin cá nhân'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);	
	$form['personal_info']['ho_ten'] = array(
		'#type' => 'textfield',
		'#title' => t('Họ và tên'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['dia_chi'] = array(
		'#type' => 'textfield',
		'#title' => t('Địa chỉ'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['dien_thoai'] = array(
		'#type' => 'textfield',
		'#title' => t('Số điện thoại'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['send'] = array(
		'#type' => 'submit',
		'#value' => t('Gửi đi'),
		'#prefix'=> '',
		'#suffix'=> '',
	);
	return $form;
}
function reg_buy_submit($form, &$form_state){
	global $user;
	$node = new stdClass();
	$node->status = 1;
	$node->type = 'buy';
	$node->created = time();
	$node->changed  = time();
	$node->title  = $form['personal_info']['dia_chi']['#value'];
	$node->uid = $user->uid;
	$node->field_buy_loaixe[0]['value'] = $form['quan_tam']['loai_xe'];
	$node->field_buy_thoidiem[0]['value'] = $form['quan_tam']['thoi_diem_mua']['#value'];
	$node->field_buy_yeucau[0]['value'] = $form['quan_tam']['yeu_cau_them']['#value'];
	$node->field_buy_hoten[0]['value'] = $form['personal_info']['ho_ten']['#value'];
	$node->field_buy_dienthoai[0]['value'] = $form['personal_info']['dien_thoai']['#value'];
	$node = node_save($node);
	smo('Bạn đã đăng ký thành công!');
}
function reg_maintenance($form_state){
	$form['quan_tam'] = array(
		'#type' => 'fieldset',
		'#title' => t('Chi nhánh và phương tiện'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);
	$form['quan_tam']['loai_xe'] = array(
		'#type' => 'select',
		'#title' => t('Loại xe'),
		'#default_value'=> '',
		'#options' => loai_xe(),
		'#required' => FALSE,
	);	
	
	$form['personal_info'] = array(
		'#type' => 'fieldset',
		'#title' => t('Thông tin cá nhân'),		
		'#tree' => TRUE,
		'#prefix'=> '<div class="wrap-form">',
		'#suffix'=> '</div>',
	);	
	$form['personal_info']['ho_ten'] = array(
		'#type' => 'textfield',
		'#title' => t('Họ và tên'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['dia_chi'] = array(
		'#type' => 'textfield',
		'#title' => t('Địa chỉ'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['dien_thoai'] = array(
		'#type' => 'textfield',
		'#title' => t('Số điện thoại'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['bien_so'] = array(
		'#type' => 'textfield',
		'#title' => t('Biển số'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['thoi_gian'] = array(
		'#type' => 'textfield',
		'#title' => t('Thời gian (ngày/giờ)'),
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['personal_info']['yeu_cau_them'] = array(
		'#type' => 'textarea',
		'#title' => t('Yêu cầu thêm'),
		'#default_value' => '',
		'#required' => FALSE,
		'#resizable' => FALSE,
	);
	$form['send'] = array(
		'#type' => 'submit',
		'#value' => t('Gửi đi'),
		'#prefix'=> '',
		'#suffix'=> '',
	);
	return $form;
}
function reg_maintenance_submit($form, &$form_state){
	global $user;
	$node = new stdClass();
	$node->status = 1;
	$node->type = 'maintenance';
	$node->created = time();
	$node->changed  = time();
	$node->title  = $form['personal_info']['dia_chi']['#value'];
	$node->uid = $user->uid;
	$node->field_maintenance_loaixe[0]['value'] = $form['quan_tam']['loai_xe'];
	$node->field_maintenance_bienso[0]['value'] = $form['personal_info']['bien_so']['#value'];
	$node->field_maintenance_ngaygio[0]['value'] = $form['personal_info']['thoi_gian']['#value'];
	$node->field_maintenance_hoten[0]['value'] = $form['personal_info']['ho_ten']['#value'];
	$node->field_maintenance_dienthoai[0]['value'] = $form['personal_info']['dien_thoai']['#value'];
	$node->field_maintenance_yeucau[0]['value'] = $form['personal_info']['yeu_cau_them']['#value'];
	$node = node_save($node);
	smo('Bạn đã đăng ký thành công!');
}

function tinh_lai_suat($form_state){
	$form['don_vi_tinh'] = array(
		'#type' => 'select',
		'#title' => t('Đơn vị tính'),
		'#default_value'=> 'VND',
		'#prefix' => '<div class="pre-form-item">',
		'#suffix' => '<div class="clear"></div></div>',
		'#options' => array(
			'VND' => t('VND'),
			'USD' => t('USD')
		),
		'#required' => true,
	);
	$form['gia_xe'] = array(
		'#type' => 'textfield',
		'#title' => t('Giá xe ôtô'),
		'#default_value' => '',
		'#prefix' => '<div class="pre-form-item">',
		'#suffix' => '<span class="suf-don-vi-tinh">VND</span><div class="clear"></div></div>',
		'#required' => true,
	);
	$form['tien_tra_truoc'] = array(
		'#type' => 'textfield',
		'#title' => t('Số tiền trả trước'),
		'#default_value' => '',
		'#prefix' => '<div class="pre-form-item">',
		'#suffix' => '<span class="suf-don-vi-tinh">VND</span><div class="clear"></div></div>',
		'#required' => true,
	);
	$form['lai_suat'] = array(
		'#type' => 'textfield',
		'#title' => t('Lãi suất'),
		'#default_value' => '',
		'#prefix' => '<div class="pre-form-item">',
		'#suffix' => '<span class="suf-phan-tram">%</span><div class="clear"></div></div>',
		'#required' => true,
	);
	$form['thoi_han'] = array(
		'#type' => 'textfield',
		'#title' => t('Thời hạn vay'),
		'#default_value' => '',
		'#prefix' => '<div class="pre-form-item">',
		'#suffix' => '<span class="suf-thang">Tháng</span><div class="clear"></div></div>',
		'#required' => true,
	);
	$form['send'] = array(
		'#type' => 'button',
		'#value' => t('Gửi đi'),
		'#prefix'=> '',
		'#suffix'=> '',
	);
	return $form;
}
function tinh_lai_suat_submit($form, &$form_state){
	
}
function get_product($pid, $loai_id){
	$obj = db_query("SELECT node.nid AS nid, 
			node.title AS node_title, 
			node.language AS node_language, node_data_field_thongso_hinhanh.field_thongso_hinhanh_fid AS thongso_hinhanh_fid, node.type AS node_type, 
			node.vid AS node_vid, 
			node_data_field_thongso_hinhanh.field_thongso_noidung_value AS noidung_value,
			node.created AS node_created 
		FROM node node  
			INNER JOIN content_type_thongso node_data_field_thongso_loai ON node.vid = node_data_field_thongso_loai.vid 
			LEFT JOIN content_type_thongso node_data_field_thongso_hinhanh ON node.vid = node_data_field_thongso_hinhanh.vid 
		WHERE (node.status <> 0) AND (node.type in ('thongso')) AND (node_data_field_thongso_loai.field_thongso_loai_value = '". $loai_id ."') AND (node_data_field_thongso_loai.field_thongso_sanpham_nid = '". $pid ."') 
		ORDER BY node_created ASC
		");
	$aProducts = array();
	while($obj_rs = db_fetch_object($obj)){ 
		$aProducts[] = $obj_rs;
	}
	return $aProducts;
}
function count_product($pid, $loai_id){
	$obj = db_query("SELECT count(*) 
		FROM node node  
			INNER JOIN content_type_thongso node_data_field_thongso_loai ON node.vid = node_data_field_thongso_loai.vid 
			LEFT JOIN content_type_thongso node_data_field_thongso_hinhanh ON node.vid = node_data_field_thongso_hinhanh.vid 
		WHERE (node.status <> 0) AND (node.type in ('thongso')) AND (node_data_field_thongso_loai.field_thongso_loai_value = '". $loai_id ."') AND (node_data_field_thongso_loai.field_thongso_sanpham_nid = '". $pid ."') 
		ORDER BY node.created ASC
		");
	return db_result($obj);
}

function get_xecu($pid, $loai_id){
	$obj = db_query("SELECT node.nid AS nid, 
			node.title AS node_title, 
			node.language AS node_language, node_data_field_thongsoxecu_hinhanh.field_thongsoxecu_hinhanh_fid AS thongsoxecu_hinhanh_fid, node.type AS node_type, 
			node.vid AS node_vid, 
			node_data_field_thongsoxecu_hinhanh.field_thongsoxecu_noidung_value AS noidung_value,
			node.created AS node_created 
		FROM node node  
			INNER JOIN content_type_thongsoxecu node_data_field_thongsoxecu_loai ON node.vid = node_data_field_thongsoxecu_loai.vid 
			LEFT JOIN content_type_thongsoxecu node_data_field_thongsoxecu_hinhanh ON node.vid = node_data_field_thongsoxecu_hinhanh.vid 
		WHERE (node.status <> 0) AND (node.type in ('thongsoxecu')) AND (node_data_field_thongsoxecu_loai.field_thongsoxecu_loai_value = '". $loai_id ."') AND (node_data_field_thongsoxecu_loai.field_thongsoxecu_xecu_nid = '". $pid ."') 
		ORDER BY node_created ASC
		");
	$aProducts = array();
	while($obj_rs = db_fetch_object($obj)){ 
		$aProducts[] = $obj_rs;
	}
	return $aProducts;
}
function count_xecu($pid, $loai_id){
	$obj = db_query("SELECT count(*) 
		FROM node node  
			INNER JOIN content_type_thongsoxecu node_data_field_thongsoxecu_loai ON node.vid = node_data_field_thongsoxecu_loai.vid 
			LEFT JOIN content_type_thongsoxecu node_data_field_thongsoxecu_hinhanh ON node.vid = node_data_field_thongsoxecu_hinhanh.vid 
		WHERE (node.status <> 0) AND (node.type in ('thongsoxecu')) AND (node_data_field_thongsoxecu_loai.field_thongsoxecu_loai_value = '". $loai_id ."') AND (node_data_field_thongsoxecu_loai.field_thongsoxecu_xecu_nid = '". $pid ."') 
		ORDER BY node.created ASC
		");
	return db_result($obj);
}
?>
